services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
          MYSQL_ROOT_PASSWORD: qwerty
          MYSQL_DATABASE: vkakids
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/sql
    command:
      --bind-address=0.0.0.0
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app_container
    environment: 
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=qwerty
      - DB_NAME=vkakids
      - DB_PORT=3306
    depends_on: 
      - db
    ports:
      - "2088:2088"
    networks:
      - app-network

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: python_bot_container
    stdin_open: true 
    tty: true       
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
